name: Deploy La pâte brisée

"on":
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Injetar API Key do Brevo
        run: sed -i 's/SUA_API_KEY_AQUI/${{ secrets.BREVO_API_KEY }}/g' index.html

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Empacotar arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
